# SPDX-FileCopyrightText: 2024 Shota FUJI <pockawoooh@gmail.com>
#
# SPDX-License-Identifier: Apache-2.0

name: Check files are correctly formatted

on:
  push:
    # Runs on every push
    branches:
      - "*"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache swiftformat
        id: cache-swiftformat
        uses: actions/cache@v4
        with:
          path: /home/runner/.gha_swifttools/swiftformat
          key: ${{ runner.os }}-swiftformat
      - name: Install swiftformat
        if: steps.cache-swiftformat.outputs.cache-hit
        shell: bash
        run: |
          echo "/home/runner/.gha_swifttools" >> $GITHUB_PATH
      - name: Download and Install swiftformat
        if: steps.cache-swiftformat.outputs.cache-hit != 'true'
        shell: bash
        run: |
          curl -SLO https://github.com/nicklockwood/SwiftFormat/releases/download/0.54.3/swiftformat_linux.zip
          unzip swiftformat_linux.zip
          rm swiftformat_linux.zip
          mkdir -p ~/.gha_swifttools
          mv swiftformat_linux ~/.gha_swifttools/swiftformat
          echo "/home/runner/.gha_swifttools" >> $GITHUB_PATH
      - name: Check format with dprint
        uses: dprint/check@v2.2
